config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'

  get 'articles/create'

  get 'booking/index'

  get 'books/index'
  resources :books
  resources :stores, only: 'create'
  resources :articles
  resources :forms
  get 'site/index'
  get 'stores/simple_form'
  get 'basics/index'
  get 'stores/theater'
  get 'stores/new'
  get 'stores/login'
  get 'stores/create'
  get 'stores/check'
  post 'stores/check'
  get 'stores/index'
  get 'stores/store'
  get 'stores/theater_store'
  post 'stores/theater_store'
  get 'stores/movie'
  get 'stores/movie_store'
  post 'stores/movie_store'
  get 'stores/movie_theaters'
  get 'stores/movie_theater_store'
  get 'stores/movie_theaters'
  post 'stores/movie_theater_store'
  get 'stores/movie_theater_store'
  get 'stores/theater'
  get 'stores/movie'
  get 'basics/new'
  post 'forms/new'
  
  

end

app/models/address.rb
class Address < ActiveRecord::Base
has_one :zip
belongs_to :theater
<<<<<<< HEAD
validations :id,presence: true
=======
>>>>>>> 99c8cb570a09a0eedc56d95b45bb94ea718f7527
end

app/models/article.rb
class Article < ActiveRecord::Base
	
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/form.rb
class Form < ActiveRecord::Base
end

app/models/movie_theater.rb
class MovieTheater < ActiveRecord::Base
belongs_to :movie
belongs_to :theater
has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_basic.rb
class UserBasic < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def create
  	            @article = Article.new(article_params)
            @article.save
            redirect_to @article
end
 
private
            def article_params
                        params.require(:article).permit(:title, :text)
            end
  end

app/controllers/basics_controller.rb
class BasicsController < ApplicationController
  def index

  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books= Book.all

  end
  def update
  	@book=Book.find(params[:id])
  	if @book.update(book_params)
  		rediredt_to(@book)
  		else
  			render "stores/login"
  	end
  end
  def show 
   @book=Book.find(params[:id])
   
end
   
 
  
  private 
    def book_params
     params.require(:book).permit(:name,:pages)
     end		
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
 def index
 	@forms=User.all
 end
 def new
 	@form=Form.new
 end
 def create
 	@form= Form.new(params[:sampleform])
 	if @form.save
 		redirect_to forms_path
 	end
 	end
 	def destroy
 	 @form=Form.find_by_id(params[:id])
 	 if @form.destroy
 	   redirect_to forms_path
 	  end
 	  end
 	  
 	  def form
 	  	@form=Form.new
 	  end
 	  def show
 	  end
 	  end 	

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
  	@custmer=Custmer.new   #here create object for Custmer model
  end
  
  def create 
   @custmer=Custmer.new(add_params) # create used for add the records to the database	
     if @custmer.save
     	redirect_to stores_login_path, :notice => "regeisterd sucessfull"
     else
        redirect_to stores_new_path, :notice =>  "registration failure"	
     end
   end 
   def index
    @custmers=Custmer.all
   end
   def login
  	@custmer=Custmer.new
  end
   def check
    @verify=Custmer.new(data_params)
    @count=0
     @obj=Custmer.all
     @obj.each do |object|
       if (@verify.email==object.email && @verify.password==object.password)
        if object.role== "admin"
          redirect_to stores_theater_path,:notice => "admin"
          session[:username]=object.name
        else
          redirect_to stores_store_path(custmer_id:object.id)
          session[:username]=object.name
          session[:user_id]=object.id
        end
      end
    end
        


end
def theater
  @theater=Theater.new
end
def theaters_store
 @theater= Theater.new(theater_params)
 if(theater.save)
  redirect_to stores_store_path
  else
  redirect_to stores_theater_path
  end
 end 
def movie
  @movie=Movie.new
end
def movies_store
 @movie=Movie.new(movie_params)
  if(@movie.save)
   redirect_to stores_store_patth
  else
   redirect_to stores_movie_path
  end
end  
def movie_theaters
 @theater=Theater.all
 @movie=Movie.all
 @movie_theater=MovieTheater.new
end
def movie_theaters_store
 @movie_theater=MovieTheater.new(movie_theater_params)
 @count=0
 @check=MovieTheater.all
 @check.each do |object|
        if(object.movie_id==@movie_theater.movie_id&&object.theater_id==@movie_theater.theater_id)
          @count+=1
        end
      end
          if @count==1
          redirect_to tickets_movie_theaters_path ,:notice=>"Registration Failure"
         else
           @theater=Theater.find(@movie_theater.theater_id)
           @movie=Movie.find(@movie_theater.movie_id)
          @movie_the=MovieTheater.create(theater_id: @theater.id ,movie_id: @movie.id)
          redirect_to tickets_store_path ,:notice=>"Registration Succesfully"

          end

    end  
 def bookings
   @movie=Movie.all  
   @theater=Theater.all
 end
 def bookings_store
   @movie_id=params[:movie_id]
   @theater_id=params[:theater_id]
   if(@movie_id!=nil)
     @movie=Movie.find(@movie_id)
   else
     @theater=Theater.find(@theater_id) 
   end
   @allTheaters= Theater.joins(:movies).where(:movies=>{id:movie_id})
   @count=Theater.joins(:movies).where(:movies=>{id:@movie_id}).count
     @allMovies=Movie.joins(:theaters).where(:theaters=>{id:@theater_id})
    @Moviecount=Movie.joins(:theaters).where(:theaters=>{id:@theater_id}).count
    end        

private
def add_params
  params.require(:custmer).permit(:name,:email,:password,:mobile)
end
def data_params
  params.require(:custmer).permit(:email,:password)
 end
 end 

def theater_params
  params.require(:theater).permit(:t_name,:t_owner,:t_no_of_seats)
end
def movie_params
  params.require(:movie).permit(:movie_name,:movie_director)
end  
def movie_theater_params
   params.require(:movie_theater).permit(:movie_id, :theater_id)
end   

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/form.html.erb
<%= form_for :article do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  </p>
  <p>
       <%= f.label :text %>
       <%= f.text_area :text %>
            </p>
            <p>
              <%= f.submit %>
            </p>
<% end %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/basics/index.html.erb
<h1 align="center">Movie_Tickets_Booking </h1>

app/views/basics/new.html.erb
<h1> hai
andrea@mbair ~/Works/12dos/bookmarks % rails generate scaffold bookmark title:string url:string
    invoke  active_record
    create    db/migrate/20130614142337_create_bookmarks.rb
    create    app/models/bookmark.rb
    invoke  resource_route
     route    resources :bookmarks
    invoke  scaffold_controller
    create    app/controllers/bookmarks_controller.rb
    [...]
    </h1><hr><h3>Packt Publishing <span class="label label-default">New Books!</span></h3>
    <%= render "" %>

app/views/booking/index.html.erb
<h1>Booking#index</h1>
<p>Find me in app/views/booking/index.html.erb</p>

app/views/forms/_form.html.erb
<center><h1> Registration_form</h1><%= form_for @form do |f| %>
<p>
<div class="form-group">
<%= f.label :firstname ,class: "col-sim-2 control-label"%>
<%= f.text_field :first_name,class: "form-control col-sm-10" %>

</div>
</p>
<p>
<%= f.label :lastname ,class: "col-md-4 control-label"%>
<%= f.text_field :last_name,class: "form-control col-mod-6" %>
</p>
<p>
<%= f.label :gender ,class: "col-md-4 control-label"%>
<%= f.radio_button :gender,'Male' %>Male
<%= f.radio_button :gender, 'Female'%>female
</p>
<p>
<%= f.label :address ,class: "col-md-4 control-label"%>
<%= f.text_area :address , :cols => "30", :rows => "4" ,class: "form-control col-mod-6"%>
</p>
<p>
<%= f.label :country,class: "col-md-4 control-label" %>
<%= f.select :country, ["india"],class: "form-control col-mod-6" %>
</p>
<%= f.submit "Submit" ,class: "btn btn-primary" %></center>
<% end %>
<hr>

app/views/forms/index.html.erb
<%= link_to "create new user",new_form_path %>
<% @forms.each do |form| %>
	firstname:<%= form.first_name %>
	lastname:<%= form.last_name %><br>
	gender : <%= form.gender %><br>
	address: <%= new_form_path.address %><br>
	country : <%= form.country %><br>
	<%= link_to "delete user" ,form_path(user),:data => {:confirm => "are you sure"}, :method => :delete %>
	<% end %>

app/views/forms/new.html.erb
<center>enter your information</center>

<%= render partial: 'form' %>

app/views/forms/show.html.erb
<h1>show</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">


 <h1 align="center">thank you</h1><hr>
 

 
</footer>

app/views/layouts/_header.html.erb
<div class="container">
   <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
       <%= button_tag(:type => 'button') do %>

        <%= link_to "About", '#'%>
        <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right" class= "list-inline"class= "bg-primary" >
            <li><%= link_to "index" %></li>
            <li><%= link_to "admin_login",   '#' %></li>
            <li><%= link_to "custmer_Log in", '#' %></li>
          </ul>
        </nav>

      </div>
    </header>
  
</div>

</body>
</html>

app/views/layouts/_header1.html.erb
<h1 align="center" class= bg-primary> Movie Ticket Booking </h1><hr>
<ol class="breadcrumb" >

<li><%= link_to "home" %></li>
<li><%= link_to 'Login',controller:"stores" ,:action=> 'login'%></li>
<li><%= link_to 'registration' %></li>

</ol><hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DynamicApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render "layouts/header1" %>

 <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>   
 
  <%= yield %>

   
 <%= render 'layouts/footer' %> 

</body>

</html>

app/views/site/index.html.erb
<div class="row">
  <div class="col-sm-12 text-center bootstrap-welcome">
    <h1>Bootstrap 4 Works!</h1>
    <p class="lead">Go ahead and build your awesome app now.</p>
  </div>
</div>

app/views/stores/index.html.erb
<h1> total information</h1>

app/views/stores/login.html.erb
<div class= "form-group">
<center><h1> login_form</h1>
<%= form_for @custmer,url:{:action=>'check'} do |f| %>
<%= f.label :Email %>
<%= f.email_field :email %>
<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>
<%= f.submit "Sumbmit" %>

<% end %></center>
</div>

app/views/stores/movie.html.erb
<h1 align="center">Movies_registration</h1><hr>
<center><b>Registration</b>
<%= form_for(@movie,url:{:action=>"movie_store"}) do |f| %>
<p>
<%= f.label :moviename %>
<%= f.text_field :movie_name %>
</p>
<p>
<%= f.label :movie_director%>
<%= f.text_field :movie_director %>
</p>
<%= f.submit "submit" %></center>
<% end %>

app/views/stores/movie_store.html.erb
<h1 align="center">Movies_Store</h1>

app/views/stores/movie_theater_store.html.erb
<h1> Movie_Theater_Store</h1>

app/views/stores/movie_theaters.html.erb
<fieldset>
	<h1 align="center"> Theater_Information</h1><hr>
	<table>
	  <tr>
	   <td>
	    <h1>Theaer_Id </h1>
	   </td>
	   <td>
	    <h3> Theater_Name</h3>
	   </td>
	   <td>
	     <h1> Theater_owner_Name </h1>
	   </td>
	   <td> 
	     <h1> No_Of_Seates </h1>
	   </td>
	  </tr>
<% @theater.each do |theater| %>
<tr>
 <td>
  <h1>
   <%= theater.id%>
  </h1>
 </td>
 <td>
   <h1>
    <%= theater.t_name %>
   </h1>
 </td>
 <td>
    <h1>
     <%= theater.t_owner %>
    </h1>
 </td>
 <td>
    <h1>
      <%= theater.t_no_of_seats %>
    </h1>
 </td>
 </tr>
 <% end %>
 </table>
 <h1> Movie_Details </h1>
 <table>
   <tr>
     <td>
      <h1>Movie_Id </h1>
     </td>
     <td>
      <h1>Movie_Name </h1>
     </td>
     <td>
      <h1>Movie_director </h1>
     </td>
    </tr>
   <% @movie.each do |movie| %>
   <tr>
    <td>
     <h1>
       <%=movie.id %>
     </h1>
    </td>
    <td>
      <h1>
       <%= movie.movie_name %>
      </h1>
    </td>
    <td>
       <h1>
        <%= movie.movie_director %>
       </h1>
    </td>
  </tr>
<% end %>
 
<p> Registratoin</p>
<h1> Theaters Registration </h1>
<p>Registration</p>
<%= form_for(@movie_theater,url:{:action=>"movie_theater_store"}) do |f| %>
<p>
<%= f.label :Teater_Id %>
<%= f.text_field :theater_id %>
</p>
<p>
<%= f.label :Movie_Id %>
<%= f.text_field :movie_id %>
</p>
<%= f.submit "sumbmit"  %>

</table>

<% end %>
</fieldset>
           

app/views/stores/simple_form.html.erb
  <h1 align="center"> Registration_Form</h1>
  
 <center> first_name: <%= text_field :email, placeholder: 'Enter email' %></br>

  last_name:<%= text_field :password, placeholder: 'Password'  %></br>

 cse: <%= check_box_tag 'rock' , 'rock music' %></br>
 eee: <%= check_box_tag 'rock' , 'rock music' %></br>
  ece:<%= check_box_tag 'rock' , 'rock music' %>
  
</center>





    

app/views/stores/store.html.erb
<h1 align="center">Welcome_To_Store</h1>
<hr>
<%= session[:username]%>
<p><%= link_to "theaters","theater" %></p>
<p><%= link_to "Movies","movie" %></p>
<p><%= link_to "Movie_theater_store","movie_theaters" %>
</p>
<p> <%= link_to "theater","theater_store" %>
</p>

app/views/stores/theater.html.erb
<h1 align="center">Theater_Registration</h1><hr>
<center><b>Registration</b>
<%= form_for(@theater,url:{:action=>"theater_store"}) do |f| %> 
<p>
<%= f.label :theater_name %>
<%= f.text_field :t_name %>
</p>
<p>
<%= f.label :theater_owner %>
<%= f.text_field :t_owner %>
</p>
<p>
<%= f.label :seats_count %>
<%= f.text_field :t_no_of_seats %>
</p>
<%= f.submit "submit"%></center>
<% end %>

app/views/stores/theater_store.html.erb
<h1 align="center"> Theater_List</h1>